### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by TheMrLhuixx** [LoneDev6/RPGhuds#2]
Could you add the option to execute commands when a player reaches the destination point?

**Comment by LoneDev6** [comment]
This should be handled by another plugin.
Which commands do you need to run after the GPS destination is reached?

**Comment by TheMrLhuixx** [comment]
> This should be handled by another plugin. Which commands do you need to run after the GPS destination is reached?

I know that it could be handled from another plugin, but my intention was to have better precision when the player reaches the destination and when "compass_reached" ![compass_reached](https://user-images.githubusercontent.com/53408803/142899870-529774f3-6fa8-4fc7-a122-7a99c0bd5e82.png) is shown, then at that moment the commands are executed

**Comment by LoneDev6** [comment]
Nono I mean, I need an example to better understand which commands you wish to execute, let me know.

Because I doubt you want the same exact commands to be executed when you reach a spot. Maybe you also want commands to be defined in a list of set of commands, so you can decide which list of commands to execute based on the location.

For example:

```yml
commands:
  set_1:
    command_1:
      cmd: "tell %player_name% hello"
    command_2:
      cmd: "give %player_name% coal"
  set_2:
     command_1:
       cmd: "give %player_name% diamond"
```

Then run `/rpgcompass LoneDev set world -227 200 136 set_2`.

I'm just thinking out loud
